site_name: Le blog des bikininjas
site_url: https://bikininjas.github.io/
repo_url: https://github.com/bikininjas/bikininjas.github.io
repo_name: bikininjas/bikininjas.github.io
theme:
  name: dracula
plugins:
  - search
  - awesome-pages
  - blogging:
      dirs: # The directories to be included
        - docs
      features:
        tags:
          index_page: tags.md
          insert: top
      categories:
        - name: tft
          dirs:
            - tft
        - name: societe
          dirs:
            - societe
        - name: tech
          dirs:
            - tech
        - name: gaming
          dirs:
            - gaming

copyright: Copyright &copy; 2024 Bikininja