name: Code Review GPT

on:
  pull_request:
    branches: [main]

permissions:
  pull-requests: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install code-review-gpt
        run: bun i code-review-gpt

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@main
        with:
          GITHUB_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAPI_KEY }}
          MODEL: "gpt-4o-mini"
          REVIEW_LANGUAGE: "English"