name: Deploy Next.js Site

on:
  push:
    branches:
      # make sure this is the branch you are using
      - master

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install -g bun          
          bun install
      - name: Linting
        run: |
          bun add eslint@8.56.0
          bun install eslint-plugin-next --save-dev
          bun run eslint --fix

      - name: Build Project
        run: |
          bun run build
          touch out/.nojekyll # Prevents GitHub Pages from ignoring files that begin with an underscore

      - name: Official SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Next.js static export output directory
