name: MkDocs Auto Deploy

on:
  push:
    branches:
      - main  # ou master, selon votre branche principale
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@main
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-dracula-theme mkdocs-blogging-plugin


      - name: Display mkdocs.yml content
        run: cat mkdocs.yml

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site