name: MkDocs Auto Deploy

on:
  push:
    branches:
      - main  # ou master, selon votre branche principale
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@main
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-dracula-theme mkdocs-publisher

      - name: Configure MkDocs
        run: |
          if [ ! -f mkdocs.yml ]; then
            echo "site_name: Le blog des bikininjas
          theme:
            name: dracula
          plugins:
            - search
            - pub-debugger
            - pub-blog:
              teaser_marker: "<!-- plus -->"
              searchable_non_posts: false
              posts_per_page: 5
              lang: fr
              slug: blog
            - pub-obsidian
            - pub-social
            - pub-meta
            - pub-minifier
            - awesome-pages" > mkdocs.yml
          fi

      - name: Display mkdocs.yml content
        run: cat mkdocs.yml

      - name: Generate blog structure
        run: |
          mkdir -p docs/posts
          if [ ! -f docs/index.md ]; then
            echo "# Bienvenue sur le blog des bikininjas" > docs/index.md
          fi

      - name: Build MkDocs site
        run: mkdocs build

      - name: List site contents
        run: ls -R site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site